export const TOKEN_META = {
  CASEAQ6R4HVHMFIVDUZ4SMCPHF4WGO5LYVWIULITHIVYL3CNMQRIJZI4: {
    code: 'USDC',
    issuer: 'circle.io',
  },
  CCRUPGCATA4YSR4ZRCXMG5VAKPJSQINT2QS66X236YMC6OSDH3H2TEIG: {
    code: 'BLND',
    issuer: undefined,
  },
  CDMT6XD3WDV4JKOI64T4LTV4JZARSTJYEV7B2DMRANLLIO74KKEBHYNJ: {
    code: 'XLM',
    issuer: 'native',
  },
  CBFFLWGRB2DWI2NFTVBRJN2K2AOJ7IQEJYHIPE2ZSOASIRGFS257SBVJ: {
    code: 'wETH',
    issuer: 'starbridge.io',
  },
  CCJECZCHMOJAIDJEKQDZT4OT6WPAKSFHYAUZBDGCVUZ4SRPKD3ZWHOE2: {
    code: 'wBTC',
    issuer: 'starbridge.io',
  },
};
